### PR TITLE
fix: forward messages

### LINKED ISSUE #1300: Unable to forward Message with chat.forwardMessage
## Description

> WPP.chat.forwardMessage("91xxxxxx@c.us","true_91xxxxxxxx@c.us_3EB0B2E90C7D0xxxxxx6");

This Command throws this error

image

## Environment

- **WhatsApp version:** '2.2335.6'
- **WA-JS version(s):** '2.24.8'
- **Browser:** 116.0.5845.96 (Official Build) (64-bit) 
- **OS:** Ubuntu
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. WPP.chat.forwardMessage("91xxxxxx@c.us","true_91xxxxxxxx@c.us_3EB0B2E90C7D0xxxxxx6");

## Your Code
```
 WPP.chat.forwardMessage("91xxxxxx@c.us","true_91xxxxxxxx@c.us_3EB0B2E90C7D0xxxxxx6");
```

### PR DESCRIPTION
**Pull request by keyurboss**
close #1300

### CODE REVIEW

**Comment by keyurboss** [comment]
This is the fix for issue #1300 

only one issue it returns Promise<boolean> instead of Promise<RawMessage[]>

**Comment by keyurboss** [comment]
@edgardmessias  can you give me some feedbacks on this??

**Comment by edgardmessias** [comment]
@keyurboss , I will look the issues and PR today

**Comment by keyurboss** [comment]
@edgardmessias Thank you

**Pull request merged**
