### PR TITLE
fix: forwardMessagesToChats is missing from ChatStore

### PR DESCRIPTION
**Pull request by keyurboss**
```
{
    VERSION: '2.2353.0', 
    DESKTOP_BETA: false, 
    BUILD_ID: '541798574'
}

```
WA-JS: '2.28.0'

image

image

### CODE REVIEW

**Comment by keyurboss** [comment]
@edgardmessias Can you review this Thank you

**Comment by edgardmessias** [comment]
Could you please fix the checks and add a fallback for old versions?

You can use this as a base: https://github.com/wppconnect-team/wa-js/blob/5242e9c793f7d815cd8c230ef22ce39144628b77/src/whatsapp/functions/contactFunctions.ts#L170

**Comment by keyurboss** [comment]
@edgardmessias It is resolved

**Comment by keyurboss** [comment]
@edgardmessias It is resolved

**Pull request merged**
