### PR TITLE
feat: Added support for buttons (v3)

### PR DESCRIPTION
**Pull request by icleitoncosta**
/**
 * This file has been obfuscated to ensure that the button solution is 
 * not easily disseminated and remains functional for a longer period, 
 * as well as to protect the efforts of several other developers who 
 * have worked and are currently working on this solution.
 */

### CODE REVIEW

**Comment by ariona** [comment]
does this bring back support for button message?

**Comment by marcelo386** [comment]
yes it is working again

**Comment by ariona** [comment]
> yes it is working again

i've tried it, it's still  not working for me.
- The message keep showing clock icon,
- when refreshed it become red.
- the message was sent when clicking red icon & resend message
- but it only send regular message with content only

i have also commented here https://github.com/wppconnect-team/wa-js/commit/fbbf0948c93cb9ec19ac8a1c85f24c44d94824a5

Screenshot 2024-09-14 at 08 53 41

Screenshot 2024-09-14 at 08 55 59

Screenshot 2024-09-14 at 08 53 41

**Comment by ariona** [comment]
> > i've tried it, it's still not working for me.
> > 
> > * The message keep showing clock icon,
> > * when refreshed it become red.
> > * the message was sent when clicking red icon & resend message
> > * but it only send regular message with content only
> > 
> > i have also commented here [fbbf094](https://github.com/wppconnect-team/wa-js/commit/fbbf0948c93cb9ec19ac8a1c85f24c44d94824a5)
> 
> Use the updated project in the latest version This PR is broken for non beta devies

Yes.. i am using latest version, the problem occured when sending to wa business number.

https://github.com/wppconnect-team/wa-js/issues/2332

**Pull request merged**
